insert into authors (id, first_name, last_name) values (1, 'Aldwin', 'Maddison');
insert into authors (id, first_name, last_name) values (2, 'Marlene', 'Claydon');
insert into authors (id, first_name, last_name) values (3, 'Maurits', 'Brende');
insert into authors (id, first_name, last_name) values (4, 'Constantine', 'Garton');
insert into authors (id, first_name, last_name) values (5, 'Kali', 'Barends');
insert into authors (id, first_name, last_name) values (6, 'Courtnay', 'Farleigh');
insert into authors (id, first_name, last_name) values (7, 'Yorke', 'MacDwyer');
insert into authors (id, first_name, last_name) values (8, 'Cristiano', 'Peasey');
insert into authors (id, first_name, last_name) values (9, 'Tod', 'Woolaston');
insert into authors (id, first_name, last_name) values (10, 'Jen', 'Cunney');
insert into authors (id, first_name, last_name) values (11, 'Shalom', 'Rodbourne');
insert into authors (id, first_name, last_name) values (12, 'Collin', 'Spaughton');
insert into authors (id, first_name, last_name) values (13, 'Honoria', 'Matthesius');
insert into authors (id, first_name, last_name) values (14, 'Daron', 'Scarce');
insert into authors (id, first_name, last_name) values (15, 'Khalil', 'Arnull');
insert into authors (id, first_name, last_name) values (16, 'Tisha', 'Dauber');
insert into authors (id, first_name, last_name) values (17, 'Tedd', 'Burles');
insert into authors (id, first_name, last_name) values (18, 'Randie', 'Andreas');
insert into authors (id, first_name, last_name) values (19, 'Karlene', 'Granger');
insert into authors (id, first_name, last_name) values (20, 'Major', 'Mattersley');
insert into authors (id, first_name, last_name) values (21, 'Hatti', 'Skelbeck');

insert into books (id, price, price_old, title, author_id) values (1, 2271, 3149, 'Tempsoft', 18);
insert into books (id, price, price_old, title, author_id) values (2, 1857, 1329, 'Fix San', 12);
insert into books (id, price, price_old, title, author_id) values (3, 2569, 1961, 'Ventosanzap', 5);
insert into books (id, price, price_old, title, author_id) values (4, 1429, 3820, 'Toughjoyfax', 16);
insert into books (id, price, price_old, title, author_id) values (5, 2202, 2667, 'Matsoft', 5);
insert into books (id, price, price_old, title, author_id) values (6, 2954, 1399, 'Zontrax', 10);
insert into books (id, price, price_old, title, author_id) values (7, 2307, 3157, 'Lotstring', 4);
insert into books (id, price, price_old, title, author_id) values (8, 1304, 3447, 'Andalax', 3);
insert into books (id, price, price_old, title, author_id) values (9, 2099, 3218, 'Otcom', 11);
insert into books (id, price, price_old, title, author_id) values (10, 2127, 2419, 'Sub-Ex', 2);
insert into books (id, price, price_old, title, author_id) values (11, 1994, 3990, 'Zamit', 6);
insert into books (id, price, price_old, title, author_id) values (12, 1858, 1126, 'Cardify', 4);
insert into books (id, price, price_old, title, author_id) values (13, 838, 3761, 'Redhold', 13);
insert into books (id, price, price_old, title, author_id) values (14, 2147, 2606, 'Konklux', 16);
insert into books (id, price, price_old, title, author_id) values (15, 2517, 1995, 'Matsoft', 5);
insert into books (id, price, price_old, title, author_id) values (16, 912, 3350, 'Trippledex', 20);
insert into books (id, price, price_old, title, author_id) values (17, 692, 3385, 'Voyatouch', 11);
insert into books (id, price, price_old, title, author_id) values (18, 1702, 3746, 'Voltsillam', 10);


